server:
  port: 8080
  profiles:
    active: local
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    initialization-mode: always
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://awsrds.c8ptf2wgo3gb.ap-northeast-2.rds.amazonaws.com:3306/awsrds?serverTimezone=Asia/Seoul&characterEncoding=utf8mb4
    username: admin
    password: qwer1234
    data: classpath:data.sql
    mode: always
    console:
      enable: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: always # 서버 시작시 항상 classpath의 sql문을 실행하도록 설정
      continue-on-error: true # 서버 시작시 sql문을 실행할 때 오류 무시하고 계속 진행
      data-locations: classpath:sql/data.sql # 서버 시작시 dml sql문을 실행할 위치 및 파일 지정